FROM node:18.17.1
WORKDIR /Users/limjickchan/Desktop/cloundNative_limjickchan/frontend/front/workdir
COPY ./front/package.json ./front/package.json
RUN npx
COPY ./ ./
CMD ["npm", "run", "start"]
EXPOSE 3000