FROM openjdk:17
WORKDIR /Users/limjickchan/Desktop/cloundNative_limjickchan/backend/workdir
ARG JAR_FILE=build/libs
COPY ${JAR_FILE}/limjickchan-0.0.1-SNAPSHOT.jar ${JAR_FILE}/limjickchan-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/build/libs/limjickchan-0.0.1-SNAPSHOT.jar"]


